#!/bin/bash

source /usr1/ethereum/NODE/conf/.env.ini
source /usr1/ethereum/NODE/script/common_func.sh

chkParameter $1
GETH_INSTANCE=$1
GETH_CMD=$2

SCRIPT_DIR="$(dirname -- "$(readlink -f -- "$0")")"

chkPID "${SCRIPT_DIR}/pid/${GETH_INSTANCE}.pid" "${GETH_INSTANCE}"

SCADDR=GSCADDR_${GETH_INSTANCE}
SCOWNR=GSCOWNR_${GETH_INSTANCE}
SCADDR=$(eval echo "\$$SCADDR")
SCOWNR=$(eval echo "\$$SCOWNR")

#echo "SCaddr :" $(eval echo "\$$SCADDR")
#echo "SCowner:" $(eval echo "\$$SCOWNR")

GETH_CMD="chkNodeInfo('$SCADDR')"
gethAttachLocal ${GETH_INSTANCE} ${GETH_CMD}

