#!/bin/bash

source /usr1/ethereum/NODE/conf/.env.ini
source /usr1/ethereum/NODE/script/common_func.sh

chkParameter $1
GETH_INSTANCE=$1

SCRIPT_DIR="$(dirname -- "$(readlink -f -- "$0")")"

echo "=========================="
echo "geth monitoring..." ${GETH_INSTANCE}
echo "=========================="

bash  ${SCRIPT_DIR}/${GETH_INSTANCE}/3.mon_geth.sh

