#!/bin/bash

source /usr1/ethereum/NODE/conf/.env.ini
source /usr1/ethereum/NODE/script/common_func.sh

chkParameter $1
GETH_INSTANCE=$1

SCRIPT_DIR="$(dirname -- "$(readlink -f -- "$0")")"

chkPID2 "${SCRIPT_DIR}/pid/${GETH_INSTANCE}.pid" "${GETH_INSTANCE}"

echo "=========================="
echo "geth Starting..." ${GETH_INSTANCE}
echo "=========================="

bash  ${SCRIPT_DIR}/${GETH_INSTANCE}/0.start.sh

echo
echo "Check Process...."
ps -ef | grep geth | grep ${GETH_INSTANCE}
echo;echo;echo
