#!/bin/bash

source /usr1/ethereum/NODE/conf/.env.ini
source /usr1/ethereum/NODE/script/common_func.sh

chkParameter $1
GETH_INSTANCE=$1
GETH_CMD=$2

SCRIPT_DIR="$(dirname -- "$(readlink -f -- "$0")")"

chkPID "${SCRIPT_DIR}/pid/${GETH_INSTANCE}.pid" "${GETH_INSTANCE}"

gethAttachLocal ${GETH_INSTANCE} ${GETH_CMD}
